#!/usr/bin/env python

import os
import sys
import datetime

path = f"{sys.argv[1]}" if len(sys.argv) > 1 else ""

data_dir = os.getenv("DATA")
if data_dir == None:
    print("no")
    exit(1)

def linkify(file):
    file_name = file.rstrip(".md")
    name = file_name.replace('-', ' ').title()
    return f"<li><a href=\"{path}/{file_name}\">{name}</a></li>"

def linkify_date(file):
    file_name = file.rstrip(".md")
    name = file_name.replace('-', ' ').title()
    timestamp = os.path.getmtime(os.path.join(data_dir, "pages", path, file))
    date = datetime.datetime.fromtimestamp(timestamp).strftime("%a %d %b %Y")
    return f"<li><span>{date} - </span><a href=\"{path}/{file_name}\">{name}</a></li>"

def is_page(e):
    return e.endswith(".md") and not (e.startswith(".") or e == "index.md")

if len(sys.argv) >= 3 and sys.argv[2] == "by_date":
    list = map(
        linkify_date,
        sorted(
            filter(
                is_page,
                os.listdir(os.path.join(data_dir, "pages", path))
            ),
            key=lambda file: os.path.getmtime(os.path.join(data_dir, "pages", path, file)),
            reverse=True
        )
    )
else:
    list = map(
        linkify,
        sorted(
            filter(
                is_page,
                os.listdir(os.path.join(data_dir, "pages", path))
            )
        )
    )

string = "".join(list)

print(f"<ul>{string}</ul>")

