#!/usr/bin/env python

import sys

body = ""
for line in sys.stdin:
    body += line

file = sys.argv[2]
title = file[file.rfind("/") + 1:file.rfind(".")].replace(",", " ").capitalize()
if title == "Index":
    title = "NomisIV"

with open(sys.argv[1], "r") as file:
    template_html = file.read()

html = template_html
html = html.replace("{title}", title)
html = html.replace("{body}", body)

sys.stdout.write(html)
