#!/usr/bin/env python

import sys
from datetime import date

if len(sys.argv) > 1:
    if sys.argv[1] == "age":
        birthday = date(2002, 2, 19)
        today = date.today()
        print(today.year - birthday.year - ((today.month, today.day) < (birthday.month, birthday.day)))

    elif sys.argv[1] == "email":
        print("<a href=\"&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#115;&#105;&#109;&#111;&#110;&#64;&#110;&#111;&#109;&#105;&#115;&#105;&#118;&#46;&#99;&#111;&#109;\">&#115;&#105;&#109;&#111;&#110;&#64;&#110;&#111;&#109;&#105;&#115;&#105;&#118;&#46;&#99;&#111;&#109;</a>")
