#!/usr/bin/env python

import sys
import subprocess
import re

body = ""
for line in sys.stdin:
    body += line

pattern = r"\$\{(.*?)\}"
captures = re.findall(pattern, body)
for cap in captures:
    cmd = cap.split(" ")
    cmd = [ f"{sys.argv[1]}/{cmd[0]}" ] + cmd[1::]
    try:
        out = subprocess.check_output(cmd).decode("utf-8").strip()
    except subprocess.CalledProcessError as err:
        print(f"error: {err.output}", file=sys.stderr)
        exit(1)
    body = body.replace(f"${{{cap}}}", out)

print(body)
